#!/usr/bin/env bash
# ls using for loop

for file in *; do
  echo "$file" | cut -d '-' -f 2;
done
--------------------------------          ---------------
------ -------- -cdsuhsudgh8psuvg favdhb pivu hdp9uhb dabn 
adsihaupiv okd ah bjd